spring:
  security:
    oauth2:
      client:
        registration:
          <registration-id>:
            client-id: <client-id>
            client-secret: <client-secret>
            authorization-grant-type: authorization_code
            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
            scope: <scopes>
        provider:
          <provider-id>:
            authorization-uri: <authorization-uri>
            token-uri: <token-uri>
            user-info-uri: <user-info-uri>
            user-name-attribute: <user-name-attribute>
